apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: my-app
          image: badmullafo/outyet:1.0_arm
          env:
            - name: foo
              value: we-are-in-prod
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: credentials